cambiato indice argomenti nella ricerca del sito in tassonomia_argomenti
RedTurtle/design-volto-theme pull request #166
Opened 2020-11-19 10:11 UTC by giuliaghisini

2020-11-19 11:52 UTC, nzambello approved these changes

2020-11-19 11:54 UTC, nzambello requested changes
Mancano dei pezzi.
Vedi le modifiche di questi commit:
https://github.com/RedTurtle/design-volto-theme/commit/f041b72131d3fa2b3c9de4cd34f63c10737ad3fe
https://github.com/RedTurtle/design-volto-theme/commit/53b9961e89173ac207c0629ac7c5243904572971

2020-11-19 13:05 UTC, giuliaghisini commented
@nzambello sistemato

2020-11-20 12:09 UTC, nzambello approved these changes

2020-11-20 12:09 UTC, merged