Editable footer
RedTurtle/design-volto-theme pull request #172
Opened 2020-11-26 16:55 UTC by giuliaghisini

Aggiunto l'addon volto-editablefooter.

La modalità di edit del footer è uguale a quella del megamenu: è possibile definire un footer diverso per pià radici di navigazione. In questo modo si riesce a gestire anche il footer dei siti multilingua.

E' possibile definire un numero illimitato di colonne del footer. Verranno mostrate 4 colonne per riga.
Per ogni colonna è possibile decidere se mostrare o meno:
- i link dei social
- la form di iscrizione alla newsletter
- nascondere la colonna
- indicare un titolo
- indicare un link da appiccicare al titolo
- inserire un testo. Se la colonna mostra i social, il testo verrà mostrato dopo i social. Se la colonna mostra la form di iscrizione alla newsletter, il testo verrà mostrato prima della form

![Schermata 2020-11-26 alle 17 52 39](https://user-images.githubusercontent.com/51911425/100376874-8f7ee480-3010-11eb-8f4a-7ab09c81cf03.png)

2020-11-26 16:59 UTC, pnicolli commented
Dubbione: il form di iscrizione alla newsletter come te lo configura se lo spunti?
Avere le info sui social dipende dall'avere un add-on specifico installato? Onestamente non mi ricordo com'è messo volto su questo :(

2020-11-27 07:52 UTC, giuliaghisini commented
> Dubbione: il form di iscrizione alla newsletter come te lo configura se lo spunti?
> Avere le info sui social dipende dall'avere un add-on specifico installato? Onestamente non mi ricordo com'è messo volto su questo :(

Allora: nell'addon ho fatto due componenti 'segnaposto', uno per la form della newsletter e uno per i social. 
Nel tuo progetto te li puoi sovrascrivere cosi, ci metti quello che vuoi.

In design volto theme, avendo bootstrap, il componente che disegna le colonne del footer l'ho dovuto riscrivere in dvt, e dell'addon ho usato solo la action per avere i dati. In dvt avevamo già il componente dei social, e ho incluso quello, mentre per la form della newsletter ho fatto un componente dedicato, che per adesso ha solo l'html della form. Se serve usarla poi sito per sito faremo l'override di quel componente per gestire l'iscrizione

In volto non c'è nulla che ti permette di gestire i social. 
Adesso sono configurati manualmente dentro al config. Abbiamo in programma di fare un addon per volto per gestire i social.

2020-11-27 09:17 UTC, nzambello requested changes

2020-11-27 09:17 UTC, nzambello commented on src/components/ItaliaTheme/Footer/FooterNewsletterSubscribe.jsx
> +        Iscriviti per riceverla
Simpatica label, ma da tradurre

2020-11-27 09:17 UTC, nzambello commented on src/components/ItaliaTheme/index.js
> +
Perchè questo?

2020-11-27 09:18 UTC, giuliaghisini commented on src/components/ItaliaTheme/index.js
> +
mmm non mi ricordo di averlo messo io .. ci guardo

2020-11-27 09:18 UTC, giuliaghisini commented on src/components/ItaliaTheme/Footer/FooterNewsletterSubscribe.jsx
> +        Iscriviti per riceverla
ok

2020-11-27 09:31 UTC, nzambello approved these changes

2020-11-27 09:52 UTC, nzambello commented
1. Rilasciamo l'addon con un tag
2. Aggiorniamo l'addon qui
3. Controlliamo che l'addon Plone sia nel policy come dipendenza
4. Mergiamo questa PR

2020-11-30 06:51 UTC, merged