Stili stampa
RedTurtle/design-volto-theme pull request #194
Opened 2020-12-22 15:24 UTC by damiDevRT

https://redturtle.tpondemand.com/restui/board.aspx?#page=board/5034431133910786991&appConfig=eyJhY2lkIjoiNjMxQzMxODg1OTYwRDhGODAxMDM1QjMyNkUwMzE3NDIifQ==&boardPopup=userstory/14963/silent

2020-12-22 15:59 UTC, giuliaghisini commented
@damiDevRT farei anche in modo che l'immagine della lead image dei content-type, che sta dentro al div row wide-image row-full-width 
abbia un'altezza massima un po piccolina, perchè altrimenti, a seconda dell immagine che c'è, occupa tantissimo spazio inutilmente

2020-12-22 16:05 UTC, giuliaghisini commented
- se provo a stampare una pagina con i blocchi, c'è dell'inutile spazio a sx. Lo toglierei.
- metterei anche una dimensione massima per le immagini delle card (in modo che non siano troppo grandi e sprechino spazio e cartucce :-D)
<img width="529" alt="Schermata 2020-12-22 alle 17 03 24" src="https://user-images.githubusercontent.com/51911425/102908480-d2996f80-4477-11eb-8983-339cd25add52.png">
![Uploading Schermata 2020-12-22 alle 17.03.33.png…]()

2020-12-22 16:05 UTC, giuliaghisini requested changes
vedi i commenti nella Conversation

2020-12-23 09:04 UTC, damiDevRT commented
> @damiDevRT farei anche in modo che l'immagine della lead image dei content-type, che sta dentro al div row wide-image row-full-width
> abbia un'altezza massima un po piccolina, perchè altrimenti, a seconda dell immagine che c'è, occupa tantissimo spazio inutilmente

@giuliaghisini ho ridotto la grandezza massima, quando riesci prova a vedere se ti torna.
Per caso ti ricordi dove hai stampato lo screen che hai messo?
Grazie

2020-12-23 14:33 UTC, damiDevRT commented
@giuliaghisini Ho sistemato la stampa del blocco listing cardWithImageTemplate. Al momento gli altri blocchi (a parte quello delle immagini) li rimuovo dalla stampa.

2020-12-23 15:00 UTC, giuliaghisini approved these changes

2020-12-23 15:00 UTC, merged