fix: added the button to delete an image previously inserted in the '…
RedTurtle/design-volto-theme pull request #219
Opened 2021-01-21 08:49 UTC by damiDevRT

Aggiunta la possibilità di rimuovere un immagine dal widget FileWidget precedentemente salvata.

Ticket:
[https://redturtle.tpondemand.com/restui/board.aspx?#page=request/15458&searchPopup=bug/9423](https://redturtle.tpondemand.com/restui/board.aspx?#page=request/15458&searchPopup=bug/9423)

2021-01-21 09:00 UTC, nzambello requested changes
LGTM, mancano solo delle traduzioni

2021-01-21 09:00 UTC, nzambello commented on src/customizations/components/manage/Widgets/FileWidget.jsx
> +                  aria-label="delete file"
Riusciamo a tradurlo?

2021-01-21 09:00 UTC, nzambello commented on src/customizations/components/manage/Widgets/FileWidget.jsx
> +                  aria-label="delete file"
Lo stesso qui

2021-01-21 09:33 UTC, giuliaghisini requested changes
dopo avere risolto i commenti di nick per me va bene

2021-01-25 08:05 UTC, damiDevRT commented
@giuliaghisini  @nzambello Ho aggiornato la pr con le traduzioni :)

2021-01-25 11:29 UTC, giuliaghisini commented
@damiDevRT ci sono ancora dei conflitt

2021-01-29 09:46 UTC, damiDevRT commented
@giuliaghisini ho tolti conflitti

2021-01-29 09:47 UTC, nzambello approved these changes

2021-01-29 11:25 UTC, merged