add target blank to rss block links
RedTurtle/design-volto-theme pull request #227
Opened 2021-02-04 08:47 UTC by luca-bellenghi

2021-02-04 08:49 UTC, damiDev8 approved these changes

2021-02-08 08:40 UTC, nzambello requested changes
Aggiungere `rel="noopener noreferrer"`

2021-02-08 08:40 UTC, nzambello commented on src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
> +                    target="_blank"
```suggestion
                    target="_blank"
                    rel="noopener noreferrer"
```

2021-02-08 08:40 UTC, nzambello commented on src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx
> +                    target="_blank"
```suggestion
                    target="_blank"
                    rel="noopener noreferrer"
```

2021-02-18 08:48 UTC, nzambello commented
@luca-bellenghi questo branch partiva da molto indietro
mi è venuto male a fare il merge di master qui
vista l'entità delle modifiche, le ho replicate qui in un branch da master: https://github.com/RedTurtle/design-volto-theme/pull/235

2021-02-18 08:48 UTC, closed without merging