fix(a11y): document outline headings
RedTurtle/design-volto-theme pull request #241
Opened 2021-02-23 11:16 UTC by nzambello

2021-02-23 14:54 UTC, giuliaghisini requested changes

2021-02-23 14:54 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx
> +                <CardTitle tag="h3">
ok, per questo template gl stili css non sono da aggiustare?

2021-02-23 14:54 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateCompact.jsx
> +              <CardTitle tag="h3">
ok, per questo template gl stili css non sono da aggiustare?

2021-02-23 14:54 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
> +                    <CardTitle tag="h3">
ok, per questo template gl stili css non sono da aggiustare?

2021-02-23 14:54 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx
> +                      <CardTitle tag="h3">
ok, per questo template gl stili css non sono da aggiustare?

2021-02-23 14:54 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
> +                    <CardTitle tag="h3" className="title">
ok, per questo template gl stili css non sono da aggiustare?

2021-02-23 16:41 UTC, nzambello commented
@giuliaghisini no, perchè gli stili erano già imposti dal selettore sul titolo, a prescindere dal tag

2021-02-24 08:01 UTC, giuliaghisini commented
> @giuliaghisini no, perchè gli stili erano già imposti dal selettore sul titolo, a prescindere dal tag

ok, allora a posto

2021-02-24 08:01 UTC, giuliaghisini approved these changes

2021-02-25 08:30 UTC, merged