chore: added Attachment component in BandoView
RedTurtle/design-volto-theme pull request #437
Opened 2022-01-10 14:54 UTC by SaraBianchi

Aggiunto Attachment component anche nella vista dei bandi per facilitare la customizzazione dove richiesta

2022-01-11 07:26 UTC, giuliaghisini requested changes
sistemiamo anche i conflitti con il master e quella cosina, poi si può mettere in staging (mergiare su develop)

2022-01-11 07:26 UTC, giuliaghisini commented on src/components/ItaliaTheme/View/BandoView/BandoView.jsx
> +    if (item.type === 'File') {
@SaraBianchi mettiamo item.type === 'File || item.type === 'Image'. 
Se caricano un'immagine non viene mai mostrata adesso. 
Verifichiamo che funzioni

2022-01-11 14:33 UTC, SaraBianchi commented
Ok sistemato. Mergiato e pushato in develop

2022-01-18 07:33 UTC, giuliaghisini reviewed
mmm credo che manchino dei file

2022-01-18 08:25 UTC, merged