fix: persone citate
RedTurtle/design-volto-theme pull request #443
Opened 2022-01-18 16:40 UTC by MauriceRedTurtle

2022-01-18 16:47 UTC, pnicolli approved these changes

2022-01-18 17:09 UTC, giuliaghisini requested changes

2022-01-18 17:09 UTC, giuliaghisini commented on src/components/ItaliaTheme/View/Commons/CuredBy.jsx
> +    defaultMessage: 'Persone citate',
o meglio ancora, sarebbe passare un titolo diverso da 'Persone' (che rimane come default) per mostrare un titolo diverso nel caso delle persone citate nella news. 
Qeusto perchè il componente è orientato al 'A cura di' e le 'persone citate' sono un'eccezione/cosa specifica di una News

2022-01-28 18:06 UTC, pnicolli commented
Attività rimandata, per ora, a data da destinarsi. La rifacciamo nuova quando servirà, che qui intanto si accumulano conflitti.

2022-01-28 18:06 UTC, closed without merging