chore: added link to location contact
RedTurtle/design-volto-theme pull request #512
Opened 2022-05-17 08:45 UTC by SaraBianchi

2022-05-17 12:49 UTC, giuliaghisini requested changes

2022-05-17 12:49 UTC, giuliaghisini commented on src/components/ItaliaTheme/View/Commons/LocationItem.jsx
> +          {location_fo.nome_sede || (
mi sa che qua si è perso un pezzo.
Non dovrebbe essere 
`(location_fo.nome_sede || location_fo.title) &&`
?

2022-05-18 08:12 UTC, SaraBianchi commented
@giuliaghisini forse così va meglio? non sono sicura da dove venga il "nome_sede" perchè non trovo il campo corrispondente da compilare, vedo stampato sempre e solo il titolo

2022-05-18 09:09 UTC, giuliaghisini commented
> @giuliaghisini forse così va meglio? non sono sicura da dove venga il "nome_sede" perchè non trovo il campo corrispondente da compilare, vedo stampato sempre e solo il titolo

non lo so.. bisognerebbe guardare da dove viene.. per evitare casini lascierei la condizione che c'era prima, ovvero
(location_fo.nome_sede || location_fo.title)

2022-05-18 12:41 UTC, merged