Search section background
RedTurtle/design-volto-theme pull request #525
Opened 2022-06-10 09:04 UTC by Wagner3UB

Block searchSections with possibility to add an existing image to background.

2022-06-13 09:38 UTC, SaraBianchi approved these changes

2022-06-14 15:52 UTC, giuliaghisini requested changes

2022-06-14 15:52 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/SearchSections/Background.jsx
> +      backgroundImage: 'url(' + props?.image?.getURL + '/@@images/image)',
mettiamo una condizione, per cui se non c'è impostata nessuna immagine di sfondo, l'attributo style non viene messo, o meglio ancora non viene messo il div

2022-06-14 15:52 UTC, giuliaghisini commented on src/components/ItaliaTheme/Blocks/SearchSections/Body.jsx
> +      <Background image={block.image} />
no, non cambiamo il nome del componente 'SearchSectionsBackground' !!! 
i siti che lo sovrascrrivevano poi non funzionano più!!
deve rimanere il componente 'SearchSectionsBackground.
Altra cosa: gli import di dvt si fanno sempre con @italia/components/ecc... e mai come ./qualcosa, perchè altrimenti non funzionano le customizzazioni!

2022-06-15 07:30 UTC, Wagner3UB commented on src/components/ItaliaTheme/Blocks/SearchSections/Body.jsx
> +      <Background image={block.image} />
Ok! Non mi ero accorto che il component <SearchSectionBackground /> prendeva lo stesso component che volevo io. 

Cosa intendi per "import di dvt"?

2022-06-15 09:11 UTC, Wagner3UB commented
@giuliaghisini Ho creato il component BackgroundUser e messo la condizionale dentro Body, così non facciamo un step in più per il background senza immagine e decidiamo dentro body qualle scegliere.

2022-06-15 09:51 UTC, merged